# -----------
# config.toml
# -----------
#
# These are the default configuration parameters used by the app if the
# `config.toml` file is not found
#
# This file is searched for in this priority
# - /etc/app/config.toml
# - ./config.toml
#
# Environment variables have precedence over any config.toml file, see
# `contrib/example.env` for the override environment variable names

[App]
# Port = "8080"   # app port, this is the docker exposed port too
# LogLevel = "0"  # -4:Debug 0:Info (default) 4:Warn 8:Error
# RootPrefix = "" # set this if app requires example.com</prefix/>

[Sessions]
# Secret = "" # set this to persist sessions, server generated if empty

[Database]
# ConnString = "data/db.db" # sqlite by default, use `postgresql://...` URIs for other drivers

[Storage]
# Type="local"
# MaxObjectSize=100_000_000   # 100MB by default
# MaxBucketSize=1_000_000_000 # 1GB by default

[Storage.Local] # Type="local"
# Root="data/storage"
# PublicEndpointURL="" # e.g. https://example.com/local_storage_handler

[Storage.Remote] # Type="remote"
# Region="auto"
# Bucket=""
# EndpointURL="https://<cliendID>.r2.cloudflarestorage.com"
# AccessKeyID=""
# SecretAccessKey=""
# PublicEndpointURL="" # e.g. https://pub-xxx.r2.dev, https://bucket.production.com

[AuthProviders.Google]
# ClientID = ""

[AuthProviders.Facebook]
# AppID = ""
# AppSecret = ""
