# -----------
# config.toml
# -----------
#
# These are the default configuration parameters used by the app if the
# `config.toml` file is not found
#
# This file is searched for in this priority
# - /etc/app/config.toml
# - ./config.toml
#
# Environment variables have precedence over any config.toml file, see
# `example.env` for the override environment variable names

[App]
Port = "8080"   # app port, this is the docker exposed port too
LogLevel = "0"  # -4:Debug 0:Info (default) 4:Warn 8:Error
RootPrefix = "" # set this if app requires example.com</prefix/>
Secret = ""     # set this to persist sessions, server generated if empty

[DB]
ConnString = "./data/db.db" # (sqlite by default)

[Credentials.Google]
ClientID = ""

[Credentials.Facebook]
AppID = ""
AppSecret = ""

[Storage]
Type="local"                # using Type="remote" requires AWS credentials, see `example.env`
Bucket="./data/storage"     # used as bucket when Type="remote"
#                             (for example, you would set 'mybucket')
S3Bucket=""                 # ignored when using Type="local"
S3PublicURL=""              # ignored when using Type="local"
MaxObjectSize=100_000_000   # 100MB
MaxBucketSize=1_000_000_000 # 1GB
