services:
  app:
    build: .
    profiles: [default]
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    env_file:
      - .env
    restart: on-failure

  app-sqlite:
    build: .
    profiles: [sqlite]
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    environment:
      - APP_DB_DRIVER=sqlite
      - APP_DB_CONNSTR=/data/db.db
    env_file:
      - .env
    volumes:
      - sqlite-data:/data
    restart: on-failure

  app-pg:
    build: .
    profiles: [postgres]
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    environment:
      APP_DB_CONNSTR: "postgresql://${POSTGRES_USER:-postgres}@/${POSTGRES_DB:-postgres}?host=/var/run/postgresql"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pg-socket:/var/run/postgresql
    restart: on-failure

  db:
    image: postgres:17
    profiles: [postgres]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pg-socket:/var/run/postgresql

volumes:
  sqlite-data:
  pgdata:
  pg-socket:
